#!/usr/bin/env python3

"""
This will work in development on a relative folder basis
It will then work when installed in site-packages on a target system
where the runner script is in /usr/bin (or wherever)
"""
from sdk.softfire.main import start_manager

from eu.softfire.MonitoringManager import MonitoringManager
from eu.softfire.utils.monitoring.utils import config_path

def start():
    mon_manager = MonitoringManager(config_path)
    start_manager(mon_manager)

if __name__ == '__main__':
    start()
